# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        exclude: .*/migrations/
        args:
          - --in-place
          - --remove-all-unused-imports

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: .*/migrations/

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        exclude: .*/migrations/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        entry: env ENV_FILE_PATH=configurations/dev.env mypy
        exclude: .*/migrations/
        additional_dependencies:
          - python-dotenv
          - pytest
          - psycopg2-binary
          - django-extensions
          - django-stubs
          - djangorestframework
          - djangorestframework-stubs
          - django-cors-headers

  - repo: local
    hooks:
      - id: pytest-on-push
        name: Run tests before push
        entry: env ENV_FILE_PATH=configurations/dev.env pytest
        language: python
        types: [python]
        stages: [push]
