# Generated by Django 4.0.2 on 2022-02-15 16:48

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', core.fields.PrimaryKeyUUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cnpj', core.fields.CNPJField(help_text='Format: 14 numeric-only digits. E.g. 12.345.678/0001-12 -> 1234567800012', max_length=14, unique=True, verbose_name='CNPJ')),
                ('company_name', models.CharField(help_text="Also known as 'Razão Social'.", max_length=100)),
                ('commercial_name', models.CharField(help_text="Also known as 'Nome fantasia'.", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', core.fields.PrimaryKeyUUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='When the user joined the company.', verbose_name='date joined')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='companies.company')),
            ],
        ),
    ]
